name: Checks, lints, and other CI

on:
  push:
    branches:
      - main
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  check-types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: pip install hatch
      - run: hatch -e types run check
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: pip install hatch
      - run: hatch -e lint run check-format
  check-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: pip install hatch
      - run: hatch -e lint run lint
  maybe-release:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: ["check-types", "check-format", "check-lint"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: pip install hatch
      - run: gh workflow run release.yml --ref `hatch version`
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: startsWith( github.ref, 'refs/tags/')
